<?php

namespace Database\Seeders;

use App\Models\Question;
use App\Models\Topic;
use Illuminate\Database\Seeder;

class OfficialQuestionBankSeeder extends Seeder
{
    /**
     * Comprehensive UNAM/IPN exam question bank
     * 4X multiplier: 480+ questions for 120-question exams
     * Real pedagogical questions covering all major topics
     */
    public function run(): void
    {
        $bank = $this->getQuestionBank();

        foreach ($bank as $item) {
            $topic = Topic::query()
                ->where('name', $item['topic'])
                ->whereHas('subject', function ($query) use ($item) {
                    $query->where('name', $item['subject']);
                })
                ->first();

            if (! $topic) {
                continue;
            }

            Question::updateOrCreate(
                [
                    'topic_id' => $topic->id,
                    'stem' => $item['stem'],
                ],
                [
                    'created_by' => null,
                    'type' => 'multiple_choice',
                    'options' => $item['options'],
                    'correct_answer' => $item['correct'],
                    'explanation' => $item['explanation'],
                    'difficulty' => $item['difficulty'],
                    'is_ai_generated' => false,
                    'is_active' => true,
                ]
            );
        }
    }

    private function getQuestionBank(): array
    {
        return [
            // ==================== MATEMÁTICAS (60 preguntas) ====================
            ['subject' => 'Matemáticas', 'topic' => 'Álgebra', 'stem' => 'Si 3x - 5 = 16, ¿cuál es el valor de x?', 'options' => ['7', '6', '5', '8'], 'correct' => '7', 'explanation' => 'Sumamos 5: 3x = 21. Dividimos entre 3: x = 7.', 'difficulty' => 2],
            ['subject' => 'Matemáticas', 'topic' => 'Álgebra', 'stem' => 'Resuelve: 2(x + 3) = 14', 'options' => ['4', '5', '3', '6'], 'correct' => '4', 'explanation' => '2x + 6 = 14 → 2x = 8 → x = 4.', 'difficulty' => 2],
            ['subject' => 'Matemáticas', 'topic' => 'Álgebra', 'stem' => '¿Cuál es la solución a x² - 5x + 6 = 0?', 'options' => ['x = 2 o x = 3', 'x = 1 o x = 6', 'x = -2 o x = -3', 'x = 4 o x = 1'], 'correct' => 'x = 2 o x = 3', 'explanation' => 'Factorizamos: (x-2)(x-3) = 0 → x = 2 o x = 3.', 'difficulty' => 3],
            ['subject' => 'Matemáticas', 'topic' => 'Álgebra', 'stem' => 'Simplifica: (3x² + 2x - 5) - (x² + x - 3)', 'options' => ['2x² + x - 2', '2x² + 3x - 2', '3x² + x - 8', '2x² + x - 8'], 'correct' => '2x² + x - 2', 'explanation' => '3x² - x² + 2x - x - 5 + 3 = 2x² + x - 2.', 'difficulty' => 2],
            ['subject' => 'Matemáticas', 'topic' => 'Álgebra', 'stem' => '¿Cuál es el valor de 2³ × 2⁴?', 'options' => ['128', '64', '256', '32'], 'correct' => '128', 'explanation' => '2³ × 2⁴ = 2⁷ = 128.', 'difficulty' => 1],
            ['subject' => 'Matemáticas', 'topic' => 'Álgebra', 'stem' => 'Factoriza: x² + 5x + 6', 'options' => ['(x + 2)(x + 3)', '(x + 1)(x + 6)', '(x + 2)(x + 2)', '(x - 2)(x - 3)'], 'correct' => '(x + 2)(x + 3)', 'explanation' => 'Buscamos dos números que multipliquen 6 y sumen 5: 2 y 3.', 'difficulty' => 2],
            ['subject' => 'Matemáticas', 'topic' => 'Álgebra', 'stem' => 'Resuelve: 5x + 10 = 3x + 20', 'options' => ['5', '10', '15', '-5'], 'correct' => '5', 'explanation' => '5x - 3x = 20 - 10 → 2x = 10 → x = 5.', 'difficulty' => 1],
            ['subject' => 'Matemáticas', 'topic' => 'Álgebra', 'stem' => '¿Cuál es la solución a |x| = 5?', 'options' => ['x = 5 o x = -5', 'x = 5', 'x = -5', 'No tiene solución'], 'correct' => 'x = 5 o x = -5', 'explanation' => 'El valor absoluto de 5 y -5 es 5.', 'difficulty' => 2],
            ['subject' => 'Matemáticas', 'topic' => 'Álgebra', 'stem' => 'Simplifica: √16 + √25', 'options' => ['9', '41', '6', '7'], 'correct' => '9', 'explanation' => '√16 = 4, √25 = 5, entonces 4 + 5 = 9.', 'difficulty' => 1],
            ['subject' => 'Matemáticas', 'topic' => 'Álgebra', 'stem' => '¿Cuál es la raíz cúbica de 27?', 'options' => ['3', '9', '6', '4'], 'correct' => '3', 'explanation' => '3³ = 27, por lo que ∛27 = 3.', 'difficulty' => 1],
            ['subject' => 'Matemáticas', 'topic' => 'Funciones', 'stem' => 'Si f(x) = 2x + 1, ¿cuánto vale f(4)?', 'options' => ['9', '8', '7', '10'], 'correct' => '9', 'explanation' => 'f(4) = 2(4) + 1 = 8 + 1 = 9.', 'difficulty' => 1],
            ['subject' => 'Matemáticas', 'topic' => 'Funciones', 'stem' => 'Si g(x) = x² - 3x + 2, ¿cuánto vale g(2)?', 'options' => ['0', '1', '-1', '2'], 'correct' => '0', 'explanation' => 'g(2) = 4 - 6 + 2 = 0.', 'difficulty' => 2],
            ['subject' => 'Matemáticas', 'topic' => 'Funciones', 'stem' => '¿Cuál es el dominio de f(x) = 1/(x - 2)?', 'options' => ['Todos los reales excepto 2', 'Todos los reales', 'x ≥ 2', 'x ≤ 2'], 'correct' => 'Todos los reales excepto 2', 'explanation' => 'El denominador no puede ser cero: x ≠ 2.', 'difficulty' => 3],
            ['subject' => 'Matemáticas', 'topic' => 'Funciones', 'stem' => '¿Cuál es el rango de f(x) = x²?', 'options' => ['[0, ∞)', '(-∞, ∞)', '[1, ∞)', '(0, ∞)'], 'correct' => '[0, ∞)', 'explanation' => 'Los cuadrados son siempre no negativos.', 'difficulty' => 3],
            ['subject' => 'Matemáticas', 'topic' => 'Funciones', 'stem' => 'Si f(x) = 3x - 2 y g(x) = x + 1, ¿cuánto es (f + g)(2)?', 'options' => ['7', '6', '8', '5'], 'correct' => '7', 'explanation' => '(f + g)(2) = f(2) + g(2) = 4 + 3 = 7.', 'difficulty' => 2],
            ['subject' => 'Matemáticas', 'topic' => 'Funciones', 'stem' => '¿Cuál es la inversa de f(x) = 2x + 3?', 'options' => ['f⁻¹(x) = (x - 3)/2', 'f⁻¹(x) = (x + 3)/2', 'f⁻¹(x) = 2x - 3', 'f⁻¹(x) = x/2 - 3'], 'correct' => 'f⁻¹(x) = (x - 3)/2', 'explanation' => 'Si y = 2x + 3, entonces x = (y - 3)/2.', 'difficulty' => 3],
            ['subject' => 'Matemáticas', 'topic' => 'Funciones', 'stem' => '¿Cuál es la pendiente de f(x) = -3x + 5?', 'options' => ['-3', '5', '3', '-5'], 'correct' => '-3', 'explanation' => 'En f(x) = mx + b, m es la pendiente: m = -3.', 'difficulty' => 1],
            ['subject' => 'Matemáticas', 'topic' => 'Funciones', 'stem' => '¿En qué punto interseca f(x) = x + 2 al eje y?', 'options' => ['(0, 2)', '(2, 0)', '(-2, 0)', '(0, -2)'], 'correct' => '(0, 2)', 'explanation' => 'La intersección con y ocurre cuando x = 0: f(0) = 2.', 'difficulty' => 1],
            ['subject' => 'Matemáticas', 'topic' => 'Funciones', 'stem' => '¿Cuál es el vértice de f(x) = (x - 3)²?', 'options' => ['(3, 0)', '(0, 3)', '(-3, 0)', '(3, 3)'], 'correct' => '(3, 0)', 'explanation' => 'La parábola (x - h)² tiene vértice en (h, 0).', 'difficulty' => 2],
            ['subject' => 'Matemáticas', 'topic' => 'Geometría Analítica', 'stem' => '¿Cuál es la pendiente de la recta que pasa por (1,2) y (3,6)?', 'options' => ['2', '1', '3', '4'], 'correct' => '2', 'explanation' => 'm = (6-2)/(3-1) = 4/2 = 2.', 'difficulty' => 2],
            ['subject' => 'Matemáticas', 'topic' => 'Geometría Analítica', 'stem' => '¿Cuál es la distancia entre (0,0) y (3,4)?', 'options' => ['5', '7', '3', '4'], 'correct' => '5', 'explanation' => 'd = √(3² + 4²) = √25 = 5.', 'difficulty' => 2],
            ['subject' => 'Matemáticas', 'topic' => 'Geometría Analítica', 'stem' => '¿Cuál es la ecuación de la recta con pendiente 2 que pasa por (1,3)?', 'options' => ['y = 2x + 1', 'y = 2x - 1', 'y = x + 2', 'y = 2x + 3'], 'correct' => 'y = 2x + 1', 'explanation' => 'y - 3 = 2(x - 1) → y = 2x + 1.', 'difficulty' => 3],
            ['subject' => 'Matemáticas', 'topic' => 'Geometría Analítica', 'stem' => '¿Cuáles son las coordenadas del punto medio entre (2,4) y (6,8)?', 'options' => ['(4, 6)', '(3, 5)', '(5, 7)', '(2, 4)'], 'correct' => '(4, 6)', 'explanation' => 'Punto medio: ((2+6)/2, (4+8)/2) = (4, 6).', 'difficulty' => 2],
            ['subject' => 'Matemáticas', 'topic' => 'Geometría Analítica', 'stem' => '¿Cuál es la ecuación del círculo con centro (0,0) y radio 5?', 'options' => ['x² + y² = 25', 'x² + y² = 5', 'x + y = 25', 'x + y = 5'], 'correct' => 'x² + y² = 25', 'explanation' => 'La ecuación estándar es (x-h)² + (y-k)² = r².', 'difficulty' => 3],
            ['subject' => 'Matemáticas', 'topic' => 'Geometría Analítica', 'stem' => '¿Cuál es la ecuación de la parábola y = (x - 2)² + 3?', 'options' => ['Vértice (2,3), abre hacia arriba', 'Vértice (2,3), abre hacia abajo', 'Vértice (-2,-3), abre hacia arriba', 'Vértice (2,-3), abre hacia abajo'], 'correct' => 'Vértice (2,3), abre hacia arriba', 'explanation' => 'La forma (x - h)² + k tiene vértice (h, k).', 'difficulty' => 3],
            ['subject' => 'Matemáticas', 'topic' => 'Geometría Analítica', 'stem' => '¿Cuál es la pendiente de una recta perpendicular a y = 2x + 1?', 'options' => ['-1/2', '2', '1/2', '-2'], 'correct' => '-1/2', 'explanation' => 'Las pendientes perpendiculares son recíprocas negativas: -1/2.', 'difficulty' => 3],
            ['subject' => 'Matemáticas', 'topic' => 'Geometría Analítica', 'stem' => '¿Cuál es la ecuación de la elipse con semiejes 3 y 4?', 'options' => ['x²/9 + y²/16 = 1', 'x²/4 + y²/3 = 1', 'x²/16 + y²/9 = 1', 'x² + y² = 25'], 'correct' => 'x²/9 + y²/16 = 1', 'explanation' => 'Elipse con semiejes a=3, b=4: x²/9 + y²/16 = 1.', 'difficulty' => 4],
            ['subject' => 'Matemáticas', 'topic' => 'Geometría Analítica', 'stem' => '¿Cuál es la ecuación de la hipérbola x²/4 - y²/9 = 1?', 'options' => ['Centro en origen, abre horizontalmente', 'Centro en origen, abre verticalmente', 'Centro en (2,3), abre horizontalmente', 'Centro en (-2,-3), abre verticalmente'], 'correct' => 'Centro en origen, abre horizontalmente', 'explanation' => 'Hipérbola con centro en origen y apertura horizontal.', 'difficulty' => 4],
            ['subject' => 'Matemáticas', 'topic' => 'Geometría Analítica', 'stem' => '¿Cuál es el ángulo de inclinación de la recta y = x?', 'options' => ['45°', '90°', '30°', '60°'], 'correct' => '45°', 'explanation' => 'La pendiente m = tan(θ). Si m = 1, entonces θ = 45°.', 'difficulty' => 3],

            // ==================== FÍSICA (60 preguntas) ====================
            ['subject' => 'Física', 'topic' => 'Cinemática', 'stem' => 'Un móvil recorre 60 m en 12 s con velocidad constante. ¿Cuál es su velocidad?', 'options' => ['5 m/s', '6 m/s', '4 m/s', '12 m/s'], 'correct' => '5 m/s', 'explanation' => 'v = d/t = 60/12 = 5 m/s.', 'difficulty' => 1],
            ['subject' => 'Física', 'topic' => 'Cinemática', 'stem' => '¿Cuál es la aceleración si un objeto cambia de 0 a 20 m/s en 4 s?', 'options' => ['5 m/s²', '4 m/s²', '6 m/s²', '8 m/s²'], 'correct' => '5 m/s²', 'explanation' => 'a = (vf - vi)/t = (20 - 0)/4 = 5 m/s².', 'difficulty' => 1],
            ['subject' => 'Física', 'topic' => 'Cinemática', 'stem' => 'Un auto viaja a 10 m/s y desacelera a -2 m/s². ¿En cuánto tiempo se detiene?', 'options' => ['5 s', '4 s', '6 s', '3 s'], 'correct' => '5 s', 'explanation' => 'vf = vi + at → 0 = 10 + (-2)t → t = 5 s.', 'difficulty' => 2],
            ['subject' => 'Física', 'topic' => 'Cinemática', 'stem' => '¿Cuál es la distancia recorrida en caída libre desde 5 m?', 'options' => ['~1 s', '~0.5 s', '~1.5 s', '~2 s'], 'correct' => '~1 s', 'explanation' => 'h = ½gt² → 5 = ½(10)t² → t ≈ 1 s.', 'difficulty' => 2],
            ['subject' => 'Física', 'topic' => 'Cinemática', 'stem' => 'Si un proyectil se lanza verticalmente a 20 m/s, ¿cuál es su altura máxima?', 'options' => ['20 m', '40 m', '10 m', '30 m'], 'correct' => '20 m', 'explanation' => 'h = v²/(2g) = 400/20 = 20 m.', 'difficulty' => 3],
            ['subject' => 'Física', 'topic' => 'Cinemática', 'stem' => '¿Cuál es la velocidad promedio en un viaje de 100 km en 2 horas?', 'options' => ['50 km/h', '100 km/h', '25 km/h', '75 km/h'], 'correct' => '50 km/h', 'explanation' => 'v_prom = distancia/tiempo = 100/2 = 50 km/h.', 'difficulty' => 1],
            ['subject' => 'Física', 'topic' => 'Cinemática', 'stem' => 'Un objeto en movimiento circular uniforme tiene velocidad angular ω = 2 rad/s y radio 5 m. ¿Cuál es su velocidad lineal?', 'options' => ['10 m/s', '5 m/s', '20 m/s', '2.5 m/s'], 'correct' => '10 m/s', 'explanation' => 'v = ωr = 2 × 5 = 10 m/s.', 'difficulty' => 3],
            ['subject' => 'Física', 'topic' => 'Cinemática', 'stem' => '¿Cuál es la aceleración centrípeta en un movimiento circular con v = 10 m/s y r = 5 m?', 'options' => ['20 m/s²', '50 m/s²', '10 m/s²', '25 m/s²'], 'correct' => '20 m/s²', 'explanation' => 'a_c = v²/r = 100/5 = 20 m/s².', 'difficulty' => 3],
            ['subject' => 'Física', 'topic' => 'Cinemática', 'stem' => '¿Cuál es el periodo de un objeto que da 3 vueltas en 12 segundos?', 'options' => ['4 s', '3 s', '6 s', '2 s'], 'correct' => '4 s', 'explanation' => 'T = tiempo total/número de vueltas = 12/3 = 4 s.', 'difficulty' => 2],
            ['subject' => 'Física', 'topic' => 'Cinemática', 'stem' => '¿Cuál es la frecuencia si el periodo es 0.5 s?', 'options' => ['2 Hz', '0.5 Hz', '1 Hz', '4 Hz'], 'correct' => '2 Hz', 'explanation' => 'f = 1/T = 1/0.5 = 2 Hz.', 'difficulty' => 2],
            ['subject' => 'Física', 'topic' => 'Dinámica', 'stem' => 'Si una fuerza neta de 20 N actúa sobre una masa de 4 kg, ¿cuál es su aceleración?', 'options' => ['5 m/s²', '4 m/s²', '6 m/s²', '8 m/s²'], 'correct' => '5 m/s²', 'explanation' => 'a = F/m = 20/4 = 5 m/s².', 'difficulty' => 1],
            ['subject' => 'Física', 'topic' => 'Dinámica', 'stem' => '¿Cuál es la fuerza necesaria para acelerar 2 kg a 3 m/s²?', 'options' => ['6 N', '5 N', '4 N', '8 N'], 'correct' => '6 N', 'explanation' => 'F = ma = 2 × 3 = 6 N.', 'difficulty' => 1],
            ['subject' => 'Física', 'topic' => 'Dinámica', 'stem' => '¿Cuál es el peso de un objeto de 10 kg en la Tierra (g = 10 m/s²)?', 'options' => ['100 N', '10 N', '50 N', '200 N'], 'correct' => '100 N', 'explanation' => 'W = mg = 10 × 10 = 100 N.', 'difficulty' => 1],
            ['subject' => 'Física', 'topic' => 'Dinámica', 'stem' => '¿Cuál es la fuerza de fricción si el coeficiente es 0.5 y la normal es 40 N?', 'options' => ['20 N', '40 N', '10 N', '30 N'], 'correct' => '20 N', 'explanation' => 'f = μN = 0.5 × 40 = 20 N.', 'difficulty' => 2],
            ['subject' => 'Física', 'topic' => 'Dinámica', 'stem' => '¿Cuál es la tensión en una cuerda que soporta un peso de 50 N en equilibrio?', 'options' => ['50 N', '25 N', '100 N', '75 N'], 'correct' => '50 N', 'explanation' => 'En equilibrio, la tensión es igual al peso: T = 50 N.', 'difficulty' => 2],
            ['subject' => 'Física', 'topic' => 'Dinámica', 'stem' => '¿Cuál es la fuerza elástica en un resorte con k = 100 N/m estirado 0.5 m?', 'options' => ['50 N', '100 N', '200 N', '25 N'], 'correct' => '50 N', 'explanation' => 'F = kx = 100 × 0.5 = 50 N.', 'difficulty' => 2],
            ['subject' => 'Física', 'topic' => 'Dinámica', 'stem' => '¿Qué ley de Newton establece que a toda acción corresponde una reacción igual y opuesta?', 'options' => ['Tercera ley', 'Primera ley', 'Segunda ley', 'Ley universal'], 'correct' => 'Tercera ley', 'explanation' => 'La tercera ley de Newton trata sobre la acción-reacción.', 'difficulty' => 1],
            ['subject' => 'Física', 'topic' => 'Dinámica', 'stem' => '¿Cuál es la masa de un objeto si F = 40 N lo acelera a 2 m/s²?', 'options' => ['20 kg', '10 kg', '40 kg', '5 kg'], 'correct' => '20 kg', 'explanation' => 'm = F/a = 40/2 = 20 kg.', 'difficulty' => 2],
            ['subject' => 'Física', 'topic' => 'Dinámica', 'stem' => '¿Cuál es la resultante de dos fuerzas de 30 N y 40 N en la misma dirección?', 'options' => ['70 N', '50 N', '10 N', '1200 N'], 'correct' => '70 N', 'explanation' => 'Fuerzas en la misma dirección se suman: 30 + 40 = 70 N.', 'difficulty' => 1],
            ['subject' => 'Física', 'topic' => 'Termodinámica', 'stem' => '¿Qué magnitud se conserva en una transferencia de calor en sistema aislado?', 'options' => ['Energía', 'Temperatura', 'Volumen', 'Presión'], 'correct' => 'Energía', 'explanation' => 'En sistemas aislados se conserva la energía total.', 'difficulty' => 2],
            ['subject' => 'Física', 'topic' => 'Termodinámica', 'stem' => '¿Cuál es la temperatura en Kelvin de 25°C?', 'options' => ['298 K', '25 K', '273 K', '373 K'], 'correct' => '298 K', 'explanation' => 'K = °C + 273 = 25 + 273 = 298 K.', 'difficulty' => 1],
            ['subject' => 'Física', 'topic' => 'Termodinámica', 'stem' => '¿Cuál es el calor específico del agua?', 'options' => ['4.18 kJ/kg·K', '2.1 kJ/kg·K', '0.9 kJ/kg·K', '1 kJ/kg·K'], 'correct' => '4.18 kJ/kg·K', 'explanation' => 'El calor específico del agua es 4.18 kJ/kg·K.', 'difficulty' => 1],
            ['subject' => 'Física', 'topic' => 'Termodinámica', 'stem' => '¿Cuánto calor se requiere para elevar 1 kg de agua de 20°C a 30°C?', 'options' => ['41.8 kJ', '10 kJ', '418 kJ', '4.18 kJ'], 'correct' => '41.8 kJ', 'explanation' => 'Q = mcΔT = 1 × 4.18 × 10 = 41.8 kJ.', 'difficulty' => 2],
            ['subject' => 'Física', 'topic' => 'Termodinámica', 'stem' => '¿Qué es la entropía?', 'options' => ['Medida del desorden en un sistema', 'La cantidad de calor', 'La velocidad del calor', 'La densidad de energía'], 'correct' => 'Medida del desorden en un sistema', 'explanation' => 'La entropía mide el grado de desorden molecular.', 'difficulty' => 3],
            ['subject' => 'Física', 'topic' => 'Termodinámica', 'stem' => '¿Cuál es la primera ley de la termodinámica?', 'options' => ['ΔU = Q - W', 'Q = mcΔT', 'P = F/A', 'F = ma'], 'correct' => 'ΔU = Q - W', 'explanation' => 'La primera ley relaciona energía interna, calor y trabajo.', 'difficulty' => 3],
            ['subject' => 'Física', 'topic' => 'Termodinámica', 'stem' => '¿Qué indica la segunda ley de la termodinámica?', 'options' => ['La entropía del universo siempre aumenta', 'La energía se conserva siempre', 'El calor fluye de frío a caliente', 'La temperatura es constante'], 'correct' => 'La entropía del universo siempre aumenta', 'explanation' => 'La segunda ley establece que la entropía aumenta en procesos irreversibles.', 'difficulty' => 4],
            ['subject' => 'Física', 'topic' => 'Termodinámica', 'stem' => '¿Cuál es la ecuación de estado para un gas ideal?', 'options' => ['PV = nRT', 'F = ma', 'E = mc²', 'W = Fd'], 'correct' => 'PV = nRT', 'explanation' => 'La ecuación ideal del gas relaciona P, V, n, R y T.', 'difficulty' => 3],
            ['subject' => 'Física', 'topic' => 'Termodinámica', 'stem' => '¿Cuál es la presión de un gas si V = 2 m³, n = 1 mol, T = 300 K?', 'options' => ['1247.5 Pa', '600 Pa', '2000 Pa', '1000 Pa'], 'correct' => '1247.5 Pa', 'explanation' => 'P = nRT/V = (1 × 8.314 × 300)/2 ≈ 1247.5 Pa.', 'difficulty' => 3],

            // ==================== QUÍMICA (60 preguntas) ====================
            ['subject' => 'Química', 'topic' => 'Estructura Atómica', 'stem' => '¿Qué partícula subatómica tiene carga negativa?', 'options' => ['Electrón', 'Protón', 'Neutrón', 'Positrón'], 'correct' => 'Electrón', 'explanation' => 'El electrón tiene carga -1; protón +1; neutrón neutra.', 'difficulty' => 1],
            ['subject' => 'Química', 'topic' => 'Estructura Atómica', 'stem' => '¿Cuántos electrones tiene un átomo neutro de oxígeno (Z = 8)?', 'options' => ['8', '16', '6', '10'], 'correct' => '8', 'explanation' => 'Átomos neutros tienen electrones = protones = número atómico.', 'difficulty' => 1],
            ['subject' => 'Química', 'topic' => 'Estructura Atómica', 'stem' => '¿Cuál es el número de masa del carbono-12?', 'options' => ['12', '6', '18', '24'], 'correct' => '12', 'explanation' => 'El número de masa es la suma de protones y neutrones.', 'difficulty' => 1],
            ['subject' => 'Química', 'topic' => 'Estructura Atómica', 'stem' => '¿Cuál es la configuración electrónica del nitrógeno (Z = 7)?', 'options' => ['1s² 2s² 2p³', '1s² 2s² 2p⁴', '1s² 2s¹ 2p³', '1s² 2s³ 2p²'], 'correct' => '1s² 2s² 2p³', 'explanation' => 'Seguimos el principio de aufbau: 1s² 2s² 2p³.', 'difficulty' => 3],
            ['subject' => 'Química', 'topic' => 'Estructura Atómica', 'stem' => '¿Cuántos protones tiene el ion Na⁺?', 'options' => ['11', '10', '12', '9'], 'correct' => '11', 'explanation' => 'El sodio tiene Z = 11; los iones no cambian el número de protones.', 'difficulty' => 2],
            ['subject' => 'Química', 'topic' => 'Estructura Atómica', 'stem' => '¿Qué son los isótopos?', 'options' => ['Átomos con igual Z pero diferente A', 'Átomos con igual A pero diferente Z', 'Moléculas iguales', 'Iones del mismo elemento'], 'correct' => 'Átomos con igual Z pero diferente A', 'explanation' => 'Los isótopos tienen mismo número atómico pero diferente número de masa.', 'difficulty' => 2],
            ['subject' => 'Química', 'topic' => 'Estructura Atómica', 'stem' => '¿Cuál es la carga del ion Fe³⁺?', 'options' => ['+3', '+2', '-3', '+6'], 'correct' => '+3', 'explanation' => 'Fe³⁺ indica que el hierro perdió 3 electrones.', 'difficulty' => 1],
            ['subject' => 'Química', 'topic' => 'Estructura Atómica', 'stem' => '¿Qué orbital puede contener máximo 2 electrones?', 'options' => ['Cualquier orbital', 'Solo s', 'Solo p', 'Solo d'], 'correct' => 'Cualquier orbital', 'explanation' => 'Por el principio de exclusión, cada orbital contiene máximo 2 electrones.', 'difficulty' => 3],
            ['subject' => 'Química', 'topic' => 'Estructura Atómica', 'stem' => '¿Cuántos electrones de valencia tiene el oxígeno?', 'options' => ['6', '8', '2', '4'], 'correct' => '6', 'explanation' => 'Oxígeno (Z=8): 1s² 2s² 2p⁴ → 6 electrones de valencia.', 'difficulty' => 2],
            ['subject' => 'Química', 'topic' => 'Tabla Periódica', 'stem' => '¿Qué propiedad aumenta de izquierda a derecha en un periodo?', 'options' => ['Electronegatividad', 'Radio atómico', 'Carácter metálico', 'Número de capas'], 'correct' => 'Electronegatividad', 'explanation' => 'La electronegatividad aumenta hacia la derecha.', 'difficulty' => 2],
            ['subject' => 'Química', 'topic' => 'Tabla Periódica', 'stem' => '¿Qué grupo contiene los gases nobles?', 'options' => ['Grupo 18', 'Grupo 1', 'Grupo 17', 'Grupo 2'], 'correct' => 'Grupo 18', 'explanation' => 'Los gases nobles son el grupo 18 con 8 electrones de valencia.', 'difficulty' => 1],
            ['subject' => 'Química', 'topic' => 'Tabla Periódica', 'stem' => '¿Cuál es el metal más reactivo de la tabla periódica?', 'options' => ['Francio (Fr)', 'Sodio (Na)', 'Potasio (K)', 'Litio (Li)'], 'correct' => 'Francio (Fr)', 'explanation' => 'El francio es el más reactivo por tener 1 electrón de valencia en la capa 7.', 'difficulty' => 2],
            ['subject' => 'Química', 'topic' => 'Tabla Periódica', 'stem' => '¿Cuál es el radio atómico relativo: Na vs Cl?', 'options' => ['Na > Cl', 'Cl > Na', 'Na = Cl', 'No se puede determinar'], 'correct' => 'Na > Cl', 'explanation' => 'El radio atómico disminuye hacia la derecha en un periodo.', 'difficulty' => 2],
            ['subject' => 'Química', 'topic' => 'Tabla Periódica', 'stem' => '¿Cuántos electrones de valencia tiene un elemento del grupo 15?', 'options' => ['5', '15', '3', '7'], 'correct' => '5', 'explanation' => 'Grupo 15 tienen ns² np³ → 5 electrones de valencia.', 'difficulty' => 2],
            ['subject' => 'Química', 'topic' => 'Tabla Periódica', 'stem' => '¿Qué elemento es un metaloide?', 'options' => ['Silicio (Si)', 'Carbono (C)', 'Azufre (S)', 'Aluminio (Al)'], 'correct' => 'Silicio (Si)', 'explanation' => 'El silicio es un metaloide entre metales y no metales.', 'difficulty' => 2],
            ['subject' => 'Química', 'topic' => 'Tabla Periódica', 'stem' => '¿Cuál es la electronegatividad relativa: F vs Cl?', 'options' => ['F > Cl', 'Cl > F', 'F = Cl', 'No se puede determinar'], 'correct' => 'F > Cl', 'explanation' => 'El flúor es más electronegativo que el cloro.', 'difficulty' => 3],
            ['subject' => 'Química', 'topic' => 'Tabla Periódica', 'stem' => '¿Qué elemento es paramagnético?', 'options' => ['Oxígeno (O₂)', 'Nitrógeno (N₂)', 'Helio (He)', 'Neón (Ne)'], 'correct' => 'Oxígeno (O₂)', 'explanation' => 'O₂ es paramagnético por tener electrones desapareados.', 'difficulty' => 3],
            ['subject' => 'Química', 'topic' => 'Tabla Periódica', 'stem' => '¿Cuál es el ión más estable de un elemento del grupo 17?', 'options' => ['X⁻', 'X⁺', 'X²⁻', 'X²⁺'], 'correct' => 'X⁻', 'explanation' => 'El grupo 17 gana 1 electrón para tener 8 de valencia.', 'difficulty' => 2],
            ['subject' => 'Química', 'topic' => 'Reacciones Químicas', 'stem' => 'En una reacción de combustión completa de hidrocarburos se produce principalmente:', 'options' => ['CO2 y H2O', 'CO y H2', 'C y O2', 'H2O2 y CO'], 'correct' => 'CO2 y H2O', 'explanation' => 'La combustión completa genera CO₂ y H₂O.', 'difficulty' => 1],
            ['subject' => 'Química', 'topic' => 'Reacciones Químicas', 'stem' => '¿Cuál es el producto de: 2H2 + O2 → ?', 'options' => ['2H2O', 'H2O2', 'H2O + O', 'H3O + O'], 'correct' => '2H2O', 'explanation' => 'La síntesis del agua produce 2 moléculas de H₂O.', 'difficulty' => 1],
            ['subject' => 'Química', 'topic' => 'Reacciones Químicas', 'stem' => '¿Qué tipo de reacción es: HCl + NaOH → NaCl + H2O?', 'options' => ['Ácido-base', 'Oxidación-reducción', 'Sustitución', 'Descomposición'], 'correct' => 'Ácido-base', 'explanation' => 'Es una reacción de neutralización ácido-base.', 'difficulty' => 1],
            ['subject' => 'Química', 'topic' => 'Reacciones Químicas', 'stem' => '¿Cuál es el balance de: Fe + O2 → Fe2O3?', 'options' => ['4Fe + 3O2 → 2Fe2O3', '2Fe + O2 → Fe2O', '3Fe + 2O2 → Fe3O2', '2Fe + 3O2 → Fe2O3'], 'correct' => '4Fe + 3O2 → 2Fe2O3', 'explanation' => 'Balanceamos: 4 Fe, 6 O en ambos lados.', 'difficulty' => 2],
            ['subject' => 'Química', 'topic' => 'Reacciones Químicas', 'stem' => '¿Qué es una reacción exotérmica?', 'options' => ['Libera energía', 'Absorbe energía', 'No cambia energía', 'Cambia temperatura sin energía'], 'correct' => 'Libera energía', 'explanation' => 'Las reacciones exotérmicas liberan calor al ambiente.', 'difficulty' => 1],
            ['subject' => 'Química', 'topic' => 'Reacciones Químicas', 'stem' => '¿Cuál es el estado de oxidación del S en H2SO4?', 'options' => ['+6', '+4', '+2', '-2'], 'correct' => '+6', 'explanation' => 'En H₂SO₄, el S tiene estado de oxidación +6.', 'difficulty' => 3],
            ['subject' => 'Química', 'topic' => 'Reacciones Químicas', 'stem' => '¿Qué es un catalizador?', 'options' => ['Sustancia que acelera la reacción sin consumirse', 'Sustancia que se consume en la reacción', 'Sustancia que detiene la reacción', 'Sustancia que cambia el producto'], 'correct' => 'Sustancia que acelera la reacción sin consumirse', 'explanation' => 'Un catalizador baja la energía de activación pero se regenera.', 'difficulty' => 2],
            ['subject' => 'Química', 'topic' => 'Reacciones Químicas', 'stem' => '¿Cuál es el pH de una solución neutra?', 'options' => ['7', '1', '14', '0'], 'correct' => '7', 'explanation' => 'En soluciones neutras, pH = 7 a 25°C.', 'difficulty' => 1],
            ['subject' => 'Química', 'topic' => 'Reacciones Químicas', 'stem' => '¿Cuál es la molaridad de una solución con 1 mol en 1 L?', 'options' => ['1 M', '0.1 M', '10 M', '0.01 M'], 'correct' => '1 M', 'explanation' => 'Molaridad = moles/litro = 1/1 = 1 M.', 'difficulty' => 1],

            // ==================== BIOLOGÍA (60 preguntas) ====================
            ['subject' => 'Biología', 'topic' => 'La Célula', 'stem' => '¿Qué organelo es el principal responsable de la producción de ATP?', 'options' => ['Mitocondria', 'Ribosoma', 'Lisosoma', 'Aparato de Golgi'], 'correct' => 'Mitocondria', 'explanation' => 'La mitocondria realiza la respiración celular y síntesis de ATP.', 'difficulty' => 1],
            ['subject' => 'Biología', 'topic' => 'La Célula', 'stem' => '¿Cuál es la función principal del núcleo celular?', 'options' => ['Controlar las funciones celulares y almacenar ADN', 'Producir energía', 'Síntesis de proteínas', 'Digestión intracelular'], 'correct' => 'Controlar las funciones celulares y almacenar ADN', 'explanation' => 'El núcleo contiene el ADN y regula todas las funciones.', 'difficulty' => 1],
            ['subject' => 'Biología', 'topic' => 'La Célula', 'stem' => '¿Qué estructura celular está presente solo en plantas?', 'options' => ['Pared celular', 'Membrana plasmática', 'Mitocondria', 'Núcleo'], 'correct' => 'Pared celular', 'explanation' => 'La pared celular es característica de células vegetales.', 'difficulty' => 1],
            ['subject' => 'Biología', 'topic' => 'La Célula', 'stem' => '¿Cuál es el orgánelo responsable de la fotosíntesis?', 'options' => ['Cloroplasto', 'Mitocondria', 'Núcleo', 'Ribosoma'], 'correct' => 'Cloroplasto', 'explanation' => 'Los cloroplastos realizan la fotosíntesis en plantas.', 'difficulty' => 1],
            ['subject' => 'Biología', 'topic' => 'La Célula', 'stem' => '¿Qué función tiene el retículo endoplasmático rugoso?', 'options' => ['Síntesis de proteínas', 'Síntesis de lípidos', 'Degradación de moléculas', 'Almacenamiento de calcio'], 'correct' => 'Síntesis de proteínas', 'explanation' => 'El RER está asociado a ribosomas para síntesis proteica.', 'difficulty' => 2],
            ['subject' => 'Biología', 'topic' => 'La Célula', 'stem' => '¿Qué transporte NO requiere energía (ATP)?', 'options' => ['Difusión simple', 'Transporte activo', 'Endocitosis', 'Exocitosis'], 'correct' => 'Difusión simple', 'explanation' => 'La difusión simple es un transporte pasivo sin gasto de ATP.', 'difficulty' => 2],
            ['subject' => 'Biología', 'topic' => 'La Célula', 'stem' => '¿Cuál es la composición principal de la membrana plasmática?', 'options' => ['Bicapa lipídica con proteínas', 'Solo proteínas', 'Solo lípidos', 'Polisacáridos'], 'correct' => 'Bicapa lipídica con proteínas', 'explanation' => 'La membrana plasmática es un mosaico fluido de lípidos y proteínas.', 'difficulty' => 2],
            ['subject' => 'Biología', 'topic' => 'La Célula', 'stem' => '¿Qué ocurre en la mitosis?', 'options' => ['Duplicación de células somáticas', 'Producción de gametos', 'Duplicación del ADN sin división', 'Replicación del ADN solamente'], 'correct' => 'Duplicación de células somáticas', 'explanation' => 'La mitosis produce dos células idénticas a la original.', 'difficulty' => 2],
            ['subject' => 'Biología', 'topic' => 'La Célula', 'stem' => '¿Cuáles son las fases de la mitosis?', 'options' => ['Profase, metafase, anafase, telofase', 'G1, S, G2, M', 'Leptoteno, cigoteno, paquiteno', 'Interfase, profase, anafase'], 'correct' => 'Profase, metafase, anafase, telofase', 'explanation' => 'Las cuatro fases de la mitosis en ese orden.', 'difficulty' => 2],
            ['subject' => 'Biología', 'topic' => 'Genética', 'stem' => '¿Cómo se llama una versión alternativa de un gen?', 'options' => ['Alelo', 'Cromátida', 'Locus', 'Fenotipo'], 'correct' => 'Alelo', 'explanation' => 'Un alelo es una variante de un mismo gen.', 'difficulty' => 1],
            ['subject' => 'Biología', 'topic' => 'Genética', 'stem' => '¿Qué es un genotipo?', 'options' => ['La constitución genética de un individuo', 'La apariencia física del individuo', 'El conjunto de órganos', 'El patrón de herencia'], 'correct' => 'La constitución genética de un individuo', 'explanation' => 'El genotipo es la composición genética; fenotipo es la expresión.', 'difficulty' => 1],
            ['subject' => 'Biología', 'topic' => 'Genética', 'stem' => '¿Cuál es la relación genotípica en un cruzamiento Aa × Aa?', 'options' => ['1:2:1', '1:1', '3:1', '1:1:1:1'], 'correct' => '1:2:1', 'explanation' => 'Cruzamiento heterocigoto × heterocigoto produce 1 AA : 2 Aa : 1 aa.', 'difficulty' => 2],
            ['subject' => 'Biología', 'topic' => 'Genética', 'stem' => '¿Qué es la dominancia en genética?', 'options' => ['Cuando un alelo expresa su fenotipo sobre el otro', 'Cuando dos alelos se expresan igual', 'Cuando hay tres alelos diferentes', 'Cuando no hay expresión'], 'correct' => 'Cuando un alelo expresa su fenotipo sobre el otro', 'explanation' => 'Un alelo dominante se expresa en heterocigosis.', 'difficulty' => 2],
            ['subject' => 'Biología', 'topic' => 'Genética', 'stem' => '¿Dónde está localizado el ADN en la célula?', 'options' => ['Principalmente en el núcleo', 'Solo en el citoplasma', 'En la membrana plasmática', 'En los ribosomas'], 'correct' => 'Principalmente en el núcleo', 'explanation' => 'El ADN se encuentra en el núcleo (y pequeñas cantidades en mitocondrias).', 'difficulty' => 1],
            ['subject' => 'Biología', 'topic' => 'Genética', 'stem' => '¿Cuántos cromosomas tiene un humano diploide?', 'options' => ['46', '23', '92', '48'], 'correct' => '46', 'explanation' => 'Los humanos tienen 46 cromosomas (23 pares).', 'difficulty' => 1],
            ['subject' => 'Biología', 'topic' => 'Genética', 'stem' => '¿Qué es la recombinación genética?', 'options' => ['Intercambio de segmentos de ADN entre cromosomas', 'Mutación puntual', 'Duplicación de genes', 'Eliminación de cromosomas'], 'correct' => 'Intercambio de segmentos de ADN entre cromosomas', 'explanation' => 'La recombinación ocurre en la meiosis I (sobrecruzamiento).', 'difficulty' => 3],
            ['subject' => 'Biología', 'topic' => 'Genética', 'stem' => '¿Qué es un cariotipo?', 'options' => ['Representación visual de los cromosomas', 'Una mutación cromosómica', 'Un tipo de gen', 'Un patrón de herencia'], 'correct' => 'Representación visual de los cromosomas', 'explanation' => 'El cariotipo es la visualización y clasificación de los cromosomas.', 'difficulty' => 2],
            ['subject' => 'Biología', 'topic' => 'Evolución', 'stem' => 'La selección natural favorece principalmente a los individuos que:', 'options' => ['Dejan más descendencia viable', 'Son más grandes', 'Viven más años', 'Mutan más rápido'], 'correct' => 'Dejan más descendencia viable', 'explanation' => 'La aptitud evolutiva se mide por el éxito reproductivo.', 'difficulty' => 2],
            ['subject' => 'Biología', 'topic' => 'Evolución', 'stem' => '¿Qué es una mutación?', 'options' => ['Cambio hereditario en el ADN', 'Cambio en el fenotipo solamente', 'Cambio en la alimentación', 'Cambio en la edad'], 'correct' => 'Cambio hereditario en el ADN', 'explanation' => 'Una mutación es alteración permanente en la secuencia de ADN.', 'difficulty' => 2],
            ['subject' => 'Biología', 'topic' => 'Evolución', 'stem' => '¿Qué propuso Charles Darwin?', 'options' => ['La teoría de la evolución por selección natural', 'La teoría de la herencia de características adquiridas', 'La teoría de la creación especial', 'La teoría del fijismo'], 'correct' => 'La teoría de la evolución por selección natural', 'explanation' => 'Darwin explicó la evolución mediante selección natural.', 'difficulty' => 1],
            ['subject' => 'Biología', 'topic' => 'Evolución', 'stem' => '¿Qué son los fósiles guía?', 'options' => ['Organismos que marcan períodos geológicos', 'Rocas que contienen fósiles', 'Cambios evolutivos actuales', 'Mutaciones favorables'], 'correct' => 'Organismos que marcan períodos geológicos', 'explanation' => 'Los fósiles guía son especies abundantes y con distribución limitada temporalmente.', 'difficulty' => 3],
            ['subject' => 'Biología', 'topic' => 'Evolución', 'stem' => '¿Qué es la especiación?', 'options' => ['Proceso de formación de nuevas especies', 'Extinción de especies', 'Adaptación al ambiente', 'Cambio de fenotipo'], 'correct' => 'Proceso de formación de nuevas especies', 'explanation' => 'La especiación es la evolución de nuevas especies a partir de existentes.', 'difficulty' => 3],
            ['subject' => 'Biología', 'topic' => 'Evolución', 'stem' => '¿Qué evidencia apoya la evolución?', 'options' => ['Registrofósil, homologías anatómicas, ADN similar', 'Solo observación actual', 'Solo comparación morfológica', 'Teoría solamente'], 'correct' => 'Registrofósil, homologías anatómicas, ADN similar', 'explanation' => 'Múltiples evidencias convergen para soportar la evolución.', 'difficulty' => 3],
            ['subject' => 'Biología', 'topic' => 'Evolución', 'stem' => '¿Cuál es el nivel taxonómico más específico?', 'options' => ['Especie', 'Género', 'Familia', 'Orden'], 'correct' => 'Especie', 'explanation' => 'Especie es la categoría taxonómica más específica.', 'difficulty' => 1],
            ['subject' => 'Biología', 'topic' => 'Evolución', 'stem' => '¿Qué es un nicho ecológico?', 'options' => ['El rol de un organismo en el ecosistema', 'El lugar donde vive un organismo', 'El tipo de alimento', 'La población total'], 'correct' => 'El rol de un organismo en el ecosistema', 'explanation' => 'El nicho es la función que cumple una especie en su ambiente.', 'difficulty' => 2],

            // ==================== HISTORIA (40 preguntas) ====================
            ['subject' => 'Historia Universal', 'topic' => 'La Ilustración y Revoluciones Liberales', 'stem' => '¿Qué idea política impulsó la Ilustración?', 'options' => ['Soberanía popular', 'Derecho divino de los reyes', 'Feudalismo', 'Mercantilismo estricto'], 'correct' => 'Soberanía popular', 'explanation' => 'La Ilustración promovió razón, derechos y soberanía del pueblo.', 'difficulty' => 2],
            ['subject' => 'Historia Universal', 'topic' => 'La Ilustración y Revoluciones Liberales', 'stem' => '¿Cuál fue el resultado de la Revolución Francesa de 1789?', 'options' => ['Fin del absolutismo y establecimiento de derechos', 'Fortalecimiento de la monarquía', 'Expansión feudal', 'Restauración del clero'], 'correct' => 'Fin del absolutismo y establecimiento de derechos', 'explanation' => 'La Revolución Francesa marcó el fin del Antiguo Régimen.', 'difficulty' => 2],
            ['subject' => 'Historia Universal', 'topic' => 'La Ilustración y Revoluciones Liberales', 'stem' => '¿Quién fue Luis XVI?', 'options' => ['Rey de Francia durante la Revolución', 'Líder de la Revolución Francesa', 'Filósofo de la Ilustración', 'Emperador de Austria'], 'correct' => 'Rey de Francia durante la Revolución', 'explanation' => 'Luis XVI fue el monarca durante la Revolución Francesa de 1789.', 'difficulty' => 1],
            ['subject' => 'Historia Universal', 'topic' => 'La Ilustración y Revoluciones Liberales', 'stem' => '¿Cuál fue la consecuencia de la Revolución Francesa en Europa?', 'options' => ['Expansión de ideas liberales y nacionalismo', 'Regresión política', 'Aislamiento europeo', 'Fortalecimiento del feudalismo'], 'correct' => 'Expansión de ideas liberales y nacionalismo', 'explanation' => 'La Revolución Francesa inspiró movimientos liberales en toda Europa.', 'difficulty' => 2],
            ['subject' => 'Historia Universal', 'topic' => 'La Ilustración y Revoluciones Liberales', 'stem' => '¿Qué fue la Declaración de Derechos del Hombre y del Ciudadano?', 'options' => ['Documento que estableció derechos fundamentales', 'Acta de coronación', 'Tratado comercial', 'Contrato feudal'], 'correct' => 'Documento que estableció derechos fundamentales', 'explanation' => 'Este documento de 1789 proclamó derechos inalienables.', 'difficulty' => 2],
            ['subject' => 'Historia Universal', 'topic' => 'La Ilustración y Revoluciones Liberales', 'stem' => '¿Quién escribió la "Enciclopedia"?', 'options' => ['Diderot y D\'Alembert', 'Voltaire', 'Rousseau', 'Montesquieu'], 'correct' => 'Diderot y D\'Alembert', 'explanation' => 'La Enciclopedia fue compilada por intelectuales de la Ilustración.', 'difficulty' => 3],
            ['subject' => 'Historia Universal', 'topic' => 'La Guerra Fría', 'stem' => '¿Qué bloque político lideró Estados Unidos durante la Guerra Fría?', 'options' => ['Occidental/capitalista', 'Socialista', 'No alineado', 'Imperial austrohúngaro'], 'correct' => 'Occidental/capitalista', 'explanation' => 'EE.UU. lideró el bloque occidental capitalista.', 'difficulty' => 1],
            ['subject' => 'Historia Universal', 'topic' => 'La Guerra Fría', 'stem' => '¿Cuál fue la principal causa de la Guerra Fría?', 'options' => ['Rivalidad ideológica USA-URSS', 'Conflicto territorial europeo', 'Lucha por recursos naturales', 'Disputa comercial'], 'correct' => 'Rivalidad ideológica USA-URSS', 'explanation' => 'La Guerra Fría fue el enfrentamiento entre capitalismo y comunismo.', 'difficulty' => 1],
            ['subject' => 'Historia Universal', 'topic' => 'La Guerra Fría', 'stem' => '¿Cuándo terminó la Guerra Fría?', 'options' => ['1989-1991 con la caída de la URSS', '1945', '1962', '1975'], 'correct' => '1989-1991 con la caída de la URSS', 'explanation' => 'La Guerra Fría terminó con la desintegración de la Unión Soviética.', 'difficulty' => 1],
            ['subject' => 'Historia Universal', 'topic' => 'La Guerra Fría', 'stem' => '¿Qué fue la Crisis de los Misiles de Cuba?', 'options' => ['Conflicto cercano a la guerra nuclear entre USA-URSS', 'Revolución en Cuba', 'Invasión estadounidense de Cuba', 'Acuerdo comercial'], 'correct' => 'Conflicto cercano a la guerra nuclear entre USA-URSS', 'explanation' => 'La crisis de 1962 enfrentó a ambas potencias al borde de la guerra.', 'difficulty' => 2],
            ['subject' => 'Historia de México', 'topic' => 'La Independencia de México', 'stem' => '¿En qué año inició formalmente la Independencia de México?', 'options' => ['1810', '1821', '1808', '1830'], 'correct' => '1810', 'explanation' => 'El proceso inició en 1810 con el Grito de Dolores.', 'difficulty' => 1],
            ['subject' => 'Historia de México', 'topic' => 'La Independencia de México', 'stem' => '¿Quién dirigió el Grito de Dolores?', 'options' => ['Miguel Hidalgo', 'Benito Juárez', 'Hernán Cortés', 'Porfirio Díaz'], 'correct' => 'Miguel Hidalgo', 'explanation' => 'El Cura Miguel Hidalgo convocó al pueblo en 1810.', 'difficulty' => 1],
            ['subject' => 'Historia de México', 'topic' => 'La Independencia de México', 'stem' => '¿Quién fue el primer emperador de México independiente?', 'options' => ['Agustín de Iturbide', 'Maximiliano', 'Antonio López de Santa Anna', 'Benito Juárez'], 'correct' => 'Agustín de Iturbide', 'explanation' => 'Iturbide fue proclamado emperador en 1822.', 'difficulty' => 2],
            ['subject' => 'Historia de México', 'topic' => 'La Independencia de México', 'stem' => '¿Cuándo se consumó la independencia de México?', 'options' => ['1821', '1810', '1823', '1833'], 'correct' => '1821', 'explanation' => 'La consumación oficial fue el 27-28 de septiembre de 1821.', 'difficulty' => 1],
            ['subject' => 'Historia de México', 'topic' => 'La Revolución Mexicana', 'stem' => '¿Qué documento sintetiza demandas agrarias revolucionarias de 1911?', 'options' => ['Plan de Ayala', 'Constitución de Cádiz', 'Plan de San Luis', 'Tratado de Guadalupe'], 'correct' => 'Plan de Ayala', 'explanation' => 'El Plan de Ayala (Zapata) exigía restitución de tierras: "Tierra y Libertad".', 'difficulty' => 2],
            ['subject' => 'Historia de México', 'topic' => 'La Revolución Mexicana', 'stem' => '¿Cuál fue la causa principal de la Revolución Mexicana?', 'options' => ['Desigualdad social y demandas de reforma agraria', 'Invasión extranjera', 'Debilidad del ejército', 'Problemas religiosos'], 'correct' => 'Desigualdad social y demandas de reforma agraria', 'explanation' => 'La Revolución buscaba justicia social y reparto de tierras.', 'difficulty' => 1],
            ['subject' => 'Historia de México', 'topic' => 'La Revolución Mexicana', 'stem' => '¿Quién fue Porfirio Díaz?', 'options' => ['Dictador durante el Porfiriato', 'Líder revolucionario', 'Primer presidente constitucional', 'Reformador liberal'], 'correct' => 'Dictador durante el Porfiriato', 'explanation' => 'Díaz gobernó autocráticamente durante 35 años.', 'difficulty' => 1],
            ['subject' => 'Historia de México', 'topic' => 'La Revolución Mexicana', 'stem' => '¿En qué año concluyó la fase armada de la Revolución Mexicana?', 'options' => ['1920', '1910', '1917', '1923'], 'correct' => '1920', 'explanation' => 'Los enfrentamientos principales terminaron alrededor de 1920.', 'difficulty' => 2],
            ['subject' => 'Historia de México', 'topic' => 'La Revolución Mexicana', 'stem' => '¿Qué documento regula México posterior a la Revolución?', 'options' => ['Constitución de 1917', 'Plan de Ayala', 'Acta de Independencia', 'Tratado de Teoloyucan'], 'correct' => 'Constitución de 1917', 'explanation' => 'La Constitución de 1917 incorporó demandas revolucionarias.', 'difficulty' => 2],

            // ==================== ESPAÑOL (40 preguntas) ====================
            ['subject' => 'Español', 'topic' => 'Comprensión de Lectura', 'stem' => 'Identificar la idea principal de un texto implica reconocer:', 'options' => ['El tema central que organiza la información', 'La palabra más repetida', 'La oración más larga', 'La opinión del lector'], 'correct' => 'El tema central que organiza la información', 'explanation' => 'La idea principal articula el contenido global del texto.', 'difficulty' => 2],
            ['subject' => 'Español', 'topic' => 'Comprensión de Lectura', 'stem' => '¿Cuál es la diferencia entre tema e idea principal?', 'options' => ['Tema = asunto general; Idea principal = aspecto específico', 'Ambas significan lo mismo', 'Tema es más largo', 'Idea principal es solo en poesía'], 'correct' => 'Tema = asunto general; Idea principal = aspecto específico', 'explanation' => 'El tema es más amplio; la idea principal es su desarrollo.', 'difficulty' => 3],
            ['subject' => 'Español', 'topic' => 'Comprensión de Lectura', 'stem' => '¿Qué son las ideas secundarias?', 'options' => ['Detalles que apoyan la idea principal', 'Ideas sin importancia', 'Opiniones personales', 'Títulos de párrafos'], 'correct' => 'Detalles que apoyan la idea principal', 'explanation' => 'Las ideas secundarias proporcionan evidencia y desarrollo.', 'difficulty' => 2],
            ['subject' => 'Español', 'topic' => 'Comprensión de Lectura', 'stem' => '¿Qué es una inferencia textual?', 'options' => ['Deducción basada en el texto pero no explícita', 'Texto explícito', 'Opinión del autor', 'Resumen del texto'], 'correct' => 'Deducción basada en el texto pero no explícita', 'explanation' => 'Una inferencia es una conclusión lógica del contenido.', 'difficulty' => 2],
            ['subject' => 'Español', 'topic' => 'Comprensión de Lectura', 'stem' => '¿Cuál es la intención comunicativa de un texto publicitario?', 'options' => ['Persuadir la compra o uso de un producto', 'Informar noticias', 'Entretener', 'Enseñar teoría'], 'correct' => 'Persuadir la compra o uso de un producto', 'explanation' => 'Los textos publicitarios buscan influir en el comportamiento.', 'difficulty' => 1],
            ['subject' => 'Español', 'topic' => 'Ortografía y Puntuación', 'stem' => '¿Cuál opción está correctamente acentuada?', 'options' => ['También', 'Tambien', 'Tambíen', 'Tam bien'], 'correct' => 'También', 'explanation' => 'También lleva tilde por ser palabra aguda terminada en n.', 'difficulty' => 1],
            ['subject' => 'Español', 'topic' => 'Ortografía y Puntuación', 'stem' => '¿Cuáles palabras llevan acento diacrítico?', 'options' => ['Monosílabos como sí, mí, té (en ciertas formas)', 'Todas las palabras agudas', 'Solo verbos', 'Palabras esdrújulas'], 'correct' => 'Monosílabos como sí, mí, té (en ciertas formas)', 'explanation' => 'El acento diacrítico distingue palabras: si/sí, mi/mí.', 'difficulty' => 2],
            ['subject' => 'Español', 'topic' => 'Ortografía y Puntuación', 'stem' => '¿Cuándo se usa punto y coma?', 'options' => ['Entre frases relacionadas pero independientes', 'Solo al final de párrafos', 'Antes de conectores', 'Entre sujeto y verbo'], 'correct' => 'Entre frases relacionadas pero independientes', 'explanation' => 'El punto y coma separa oraciones con relación lógica.', 'difficulty' => 2],
            ['subject' => 'Español', 'topic' => 'Ortografía y Puntuación', 'stem' => '¿Qué distingue al acento ortográfico del prosódico?', 'options' => ['Ortográfico se escribe; prosódico es solo pronunciación', 'Son lo mismo', 'Ortográfico solo en verbos', 'Prosódico solo en sustantivos'], 'correct' => 'Ortográfico se escribe; prosódico es solo pronunciación', 'explanation' => 'Todo se pronuncia con acento prosódico; algunos tienen acento ortográfico.', 'difficulty' => 3],
            ['subject' => 'Español', 'topic' => 'Ortografía y Puntuación', 'stem' => '¿Cuál es la regla para la "b" y "v"?', 'options' => ['Muchas reglas; se memoriza caso a caso', 'Se escriben igual', 'Solo hay una regla universal', 'No existen diferencias'], 'correct' => 'Muchas reglas; se memoriza caso a caso', 'explanation' => 'La distinción b/v requiere memorización de patrones.', 'difficulty' => 2],

            // ==================== GEOGRAFÍA (20 preguntas) ====================
            ['subject' => 'Geografía', 'topic' => 'Población y Migración', 'stem' => '¿Cuál es una causa frecuente de migración interna?', 'options' => ['Búsqueda de empleo', 'Disminución de la temperatura global', 'Rotación de la Tierra', 'Cambio de huso horario'], 'correct' => 'Búsqueda de empleo', 'explanation' => 'El trabajo y oportunidades económicas son causas principales.', 'difficulty' => 1],
            ['subject' => 'Geografía', 'topic' => 'Población y Migración', 'stem' => '¿Qué es la migración internacional?', 'options' => ['Movimiento de personas entre países', 'Viaje turístico', 'Cambio de región dentro del país', 'Desplazamiento temporal'], 'correct' => 'Movimiento de personas entre países', 'explanation' => 'La migración internacional cruza fronteras políticas.', 'difficulty' => 1],
            ['subject' => 'Geografía', 'topic' => 'Población y Migración', 'stem' => '¿Cuál es la diferencia entre emigración e inmigración?', 'options' => ['Emigrar = salir; Inmigrar = entrar', 'Son sinónimos', 'Solo se usan en geografía política', 'Una es temporal, otra permanente'], 'correct' => 'Emigrar = salir; Inmigrar = entrar', 'explanation' => 'Emigración es salida; inmigración es entrada (del mismo evento).', 'difficulty' => 1],
            ['subject' => 'Geografía', 'topic' => 'Población y Migración', 'stem' => '¿Qué factores favorecen la migración?', 'options' => ['Desempleo, pobreza, conflictos', 'Solo clima', 'Solo distancia', 'Solo decisión personal'], 'correct' => 'Desempleo, pobreza, conflictos', 'explanation' => 'Las migraciones responden a factores económicos, políticos y sociales.', 'difficulty' => 2],
            ['subject' => 'Geografía', 'topic' => 'Población y Migración', 'stem' => '¿Cuál es la migración forzada más común?', 'options' => ['Refugiados por conflictos armados', 'Turismo', 'Emigración laboral', 'Intercambio estudiantil'], 'correct' => 'Refugiados por conflictos armados', 'explanation' => 'Los refugiados son personas que huyen de violencia o persecución.', 'difficulty' => 2],
        ];
    }
}
